### ISSUE TITLE
Unable to rebuild any UPKs in 1.52, requesting new build, SRT forum dead.

### ISSUE THREAD

**Issue by WolkenKatz** [stricq/UPKManager#11]
Using your download from the SRT site for 1.52, rebuilds don't work for me at all. This build was released in September last year, almost a year ago, and there has been changes to the code as early as 2 months ago. If this new code is stable, could you please release a new build? I'd love to mod this game and this seems to be the only workable way to do it.

Also, the forum at the SRT website is dead; you can't even create an account because the bot-checker never loads.

**Comment by stricq** [comment]
I just released v1.6.0.  I'll look into the forums registration process.  I was having a number of local network DNS issues for a while that I have now solved, maybe that fixed it.

**Comment by stricq** [comment]
I removed the reCaptcha, no idea why it stopped working.
