### ISSUE TITLE
RemoteDB Down

### ISSUE THREAD

**Issue by DemonRem** [stricq/UPKManager#18]
as you all may know the software alert us that the remotedb is not accessible why it's becuse some error with the webserver return to the software false you may see that the database is offline in the next URL:

https://raven.stricq.com/

no fix need over here, the software going to the url to collect the data she need as you can look at the picture

My URL : http://212.179.200.225:8080

**Comment by DemonRem** [comment]
guys i keep working on this project from that point you may check my svn : 

https://github.com/DemonRem/RavenManager

RemoteDB Is Fully Function.

**Comment by stricq** [comment]
I've been having trouble with the storage that the virtual machine that runs the database is on.  I'll have it back up and running in limp home mode today and fully operational next week once new SSDs arrive.

**Comment by DemonRem** [comment]
ok
