### ISSUE TITLE
UpkManager.Dds (extended support of some compression formats)

### ISSUE THREAD

**Issue by Krakean** [stricq/UPKManager#6]
@stricq 
Hello
Curious,
a) Can you add support for BC6H/BC7 to reader (and may be - compression, but cant assume how hard it would be, but source code of AMD's Compressonator is available on github, it has bc6h/bc7 impl)?
b) Is there any way to optimize compression process? May be some more unsafe/system.memory/span/simd could solve an issue? And may be refactoring inner loops would be nice, as I suppose they were copied straight away from libsquish

**Comment by stricq** [comment]
a) This is not a compression format included in the specifications for DDS.

b) I'm sure there could be some more optimizations but for the purposes of this program, its not necessary.
